import React,{useEffect} from 'react';

const TermsOfService = () => {
    useEffect(() => {
        window.scrollTo(0, 0); 
    }, []);
    return (
        <div className="container mx-auto p-6 bg-white text-gray-800 rounded-lg shadow-md max-w-2xl text-justify">
            <h1 className="text-3xl font-bold mb-4 text-secondary">Terms and Conditions</h1>
            
            <section className="mb-6">
                <h2 className="text-xl font-semibold text-gray-700 mb-2">Introduction</h2>
                <p className="text-gray-600">
                This document is an electronic record in terms of the Information Technology Act, 2000 and Rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of a computer resource.<br/>
                This User Agreement (“Agreement”) is a legal agreement between you (“you,” “your”) and Cheggout Services Private Limited (“Cheggout,” “we,” “our” or “us”) governing your use of Cheggout's services, whereby Cheggout shall provide buyable offers to you to purchase and/or facilitate transactions on your behalf (together, the “Cheggout Services”).<br/>
                When you use Cheggout, you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such services, and they shall be deemed to be incorporated into this Agreement. The Privacy Policy and Disclaimer also form part of this Agreement. We reserve the right, at our sole discretion, to change, modify, add, or remove portions of this Agreement at any time without prior written notice to you. It is your responsibility to review this Agreement periodically for updates or changes. Your continued use of Cheggout Services following the posting of changes will mean that you accept and agree to the revisions.<br/>
                This is an important document to consider carefully before using Cheggout Services. Please read the terms of this Agreement thoroughly before agreeing to it. This Agreement also highlights certain risks of using Cheggout Services and offers guidance on how online offers can be redeemed through Cheggout. You are solely responsible for understanding and complying with any laws, rules, and regulations applicable to you in your jurisdiction regarding your business and use of Cheggout Services.<br/>
                <br/>BY CLICKING THE ACCEPTANCE BUTTON OR ACCESSING, USING, OR INSTALLING ANY PART OF THE SERVICE, YOU EXPRESSLY AGREE TO AND CONSENT TO BE IRREVOCABLY BOUND BY THIS AGREEMENT AND ALL OF THE TERMS SET OUT HEREIN. IF YOU DO NOT AGREE TO ALL OF THE TERMS OF THIS AGREEMENT, SELECT THE BUTTON INDICATING NON-ACCEPTANCE, AND CHEGGOUT WILL CANCEL THE ASSOCIATION, DENYING YOU ACCESS TO USE OR INSTALL ANY PART OF THE SERVICE. CHEGGOUT SHALL DEEM TO HAVE ACCEPTED THIS AGREEMENT, AND THE CONTRACT SHALL ONLY BE CONSIDERED DULY EXECUTED, VALID, AND BINDING AFTER RECEIVING THE REQUIRED INFORMATION FROM YOU, VERIFYING IT, AND SENDING VERIFICATION OF THE CONTRACT TO YOU.<br/>
                THE CONTRACT SHALL BE DEEMED TO HAVE BEEN RECEIVED, ACCEPTED, AND FORMED AT CHEGGOUT'S REGISTERED OFFICE: Gateway Building, MG Road, Mangalore, Karnataka, India, 575003.<br/>
                This Agreement is divided into two parts. <span className='font-bold'>Part  One </span>  explains the terms governing your use of the Services. <span className='font-bold'>  Part  Two </span> contains additional legal terms, including provisions limiting our liability and requiring individual arbitration for any potential legal disputes. To use the Services, you must accept all terms of this Agreement.

                </p>
            </section>
            <section className="mb-6">
                <h2 className="text-xl font-semibold text-gray-900 mb-2">Part One: Service Terms</h2>
                <div className='pl-4 mb-6'>
                <h3 className="text-xl font-semibold text-gray-700 mb-2">1. Offer</h3>
                <p className="text-gray-600">
                The offers provided by Cheggout in partnership with IDFC FIRST Bank are subject to the following conditions:
                    <ul className="list-disc ml-6 text-gray-600">
                            <li>
                            <h3 className="text-lg font-medium mt-4">Availability:</h3>
                            <p className="mt-2">
                            Offers are exclusively available to IDFC FIRST Bank credit card holders and are subject to the bank’s terms, including eligibility based on specific Bank Identification Numbers (BINs).
                            </p>
                        </li>
                        <li>
                            <h3 className="text-lg font-medium mt-4">Expiry:</h3>
                            <p className="mt-2">
                            Each offer has a defined validity period stated at issuance. Once expired, the offer cannot be redeemed, and no extensions will be granted.
                            </p>
                        </li>
                        <li>
                            <h3 className="text-lg font-medium mt-4">Redemption Limitations:</h3>
                            <p className="mt-2">
                            Each offer may be restricted to one-time use or limited use per customer/transaction.
                            </p>
                        </li>
                        <li>
                            <h3 className="text-lg font-medium mt-4">Modification or Withdrawal:</h3>
                            <p className="mt-2">
                            Cheggout and IDFC FIRST Bank may modify or withdraw any offer at any time without prior notice.
                            </p>
                        </li>
                        <li>
                            <h3 className="text-lg font-medium mt-4">Misuse and Non-transferability:</h3>
                            <p className="mt-2">
                            Offers are for personal use only. Sharing, reselling, or unauthorized use is prohibited, and Cheggout is not responsible for any misuse.
                            </p>
                        </li>
                    </ul>
                </p>
                </div>
                
                <div className='pl-4 mb-6'>
                <h3 className="text-xl font-semibold text-gray-700 mb-2">2. Registered User</h3>
                <p className="text-gray-600">
                To access offers, users must register with accurate information, specifically a personal mobile number:
                    <ul className="list-disc ml-6 text-gray-600">
                            <li>
                            <h3 className="text-lg font-medium mt-4">Information Accuracy:</h3>
                            <p className="mt-2">
                            Users must ensure their registration details are current
                            </p>
                        </li>
                        <li>
                            <h3 className="text-lg font-medium mt-4">Verification:</h3>
                            <p className="mt-2">
                            Users complete OTP verification to access offers.
                            </p>
                        </li>
                        <li>
                            <h3 className="text-lg font-medium mt-4">Updates and Changes:</h3>
                            <p className="mt-2">
                            Users are responsible for updating registration information.
                            </p>
                        </li>
                        <li>
                            <h3 className="text-lg font-medium mt-4">Account Security:</h3>
                            <p className="mt-2">
                            Users are responsible for securing their account details.
                            </p>
                        </li>
                        <li>
                            <h3 className="text-lg font-medium mt-4">Eligibility:</h3>
                            <p className="mt-2">
                            Registration confirms eligibility as IDFC FIRST Bank credit card holders.
                            </p>
                        </li>
                    </ul>
                </p>
                </div>
                <section className="pl-4 mb-6">
                    <h3 className="text-xl font-semibold text-gray-700 mb-2">3. Usage of Offers</h3>
                    <p className="text-gray-600">
                    Users should not share their offer codes with others. Cheggout is not liable for losses from unauthorized code sharing.
                    </p>
                </section>
                <section className="pl-4 mb-6">
                    <h3 className="text-xl font-semibold text-gray-700 mb-2">4. Payment</h3>
                    <p className="text-gray-600">
                    Users must pay via IDFC FIRST Bank credit card. Offer eligibility based on specific BINs is at IDFC FIRST Bank's discretion.
                    </p>
                </section>
                <section className="pl-4 mb-6">
                    <h3 className="text-xl font-semibold text-gray-700 mb-2">5. Privacy Policy</h3>
                    <p className="text-gray-600">
                    Cheggout is committed to protecting your privacy. For details on data collection, use, and disclosure, please see our Privacy Policy.

                    </p>
                </section>
                <section className="pl-4 mb-6">
                    <h3 className="text-xl font-semibold text-gray-700 mb-2">6. Limitation of Liability</h3>
                    <p className="text-gray-600">
                    Cheggout is not liable for damages from using our services, including financial losses, data loss, or reputational harm.
                    </p>
                </section>
                <section className="pl-4 mb-6">
                    <h3 className="text-xl font-semibold text-gray-700 mb-2">7. Changes to Terms</h3>
                    <p className="text-gray-600">
                    Cheggout may modify these Terms at any time. Continued use of the services after changes indicates your acceptance.
                    </p>
                </section>
            </section>
            
            
            <section className="mb-6">
                <h2 className="text-xl font-semibold text-gray-900 mb-2">Part Two: Additional Legal Terms                </h2>
                <section className="pl-4 mb-6">
                    <h3 className="text-xl font-semibold text-gray-700 mb-2">8. Governing Law and Dispute Resolution                    </h3>
                    <p className="text-gray-600">
                    This Agreement shall be governed by and construed in accordance with the laws of Karnataka, India. Any dispute arising under this Agreement shall be resolved through individual arbitration as per the Arbitration and Conciliation Act, 1996, with the venue in Mangalore, Karnataka.
                    </p>
                </section>
                <section className="pl-4 mb-6">
                    <h3 className="text-xl font-semibold text-gray-700 mb-2">9. Severability                    </h3>
                    <p className="text-gray-600">
                    If any provision of this Agreement is found to be unenforceable or invalid, the remaining provisions will continue to be in effect.
                    </p>
                </section>
            </section>
            
            <section className="mb-6">
                <h2 className="text-xl font-semibold text-gray-900 mb-2">Contact Us                </h2>
                <p className="text-gray-600">
                For questions or concerns about these Terms and Conditions, please contact us at:
                </p>
                <ul className="list-disc ml-6 text-gray-600">
                    <li className='flex  space-x-2 items-center mt-4'>
                            <h3 className="text-lg font-medium ">Email:</h3>
                            <p className="">
                            support@cheggout.com
                            </p>
                        </li>
                        <li className='flex items-start space-x-2 mt-4'>
                            <h3 className="text-lg font-medium ">Company:</h3>
                            <p className="">
                            Cheggout Services Private Limited
                            </p>
                        </li>
                    </ul>
            </section>
        </div>
    );
};

export default TermsOfService;
